server:
  port: 8080

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  profiles:
    default: development

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

sentry:
  dsn: https://a526c1c30e031b5d79d02a977edcad74@o4508669871915008.ingest.de.sentry.io/4508669967335504
  traces-sample-rate: 1.0