spring:
  datasource:
    url: "jdbc:h2:mem:spring;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE"
    username: "Lunycat"
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console